<?php

namespace WebSocketClient;

use WebSocketClient\WebSocketClient;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-19 at 21:57:39.
 */
class WebSocketClientTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var WebSocketClient
     */
    protected $object;
    protected $client, $loop;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    public function testPingPong() {
        $loop = \React\EventLoop\Factory::create();
        $response;
        $client = new WebSocketClient($loop, SERVER_IP, SERVER_PORT, SERVER_PATH);
        $client->setOnMessageCallback(
                function (WebSocketClient $conn, $data) use (&$response, $loop) {
            $response = $data;
            $loop->stop();
        }
        );

        $loop->addPeriodicTimer(1, function () use (&$client, $loop) {
            $client->send(MessageFactory::createRequest("1", "ping"));
        });

        $loop->run();

        $this->assertEquals('pong', $response['response']['data']);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->client->disconnect();
    }

}
